version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_javacore
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - javacore_data:/var/lib/mysql

volumes:
  javacore_data: